### PR TITLE
feat: custom words blocked

### PR DESCRIPTION
**Pull request by gpedro**
allow easy blocking: prefix, name, and word in character name

### CODE REVIEW

**Comment by slawkens** [comment]
Hello, I find that latest comment wasn't good removing that from config.

What do you say if I remove it?

**Comment by gpedro** [comment]
what do u mean?

**Comment by slawkens** [comment]
I think it was good to have it configurable in config.php

That part with God, GM etc.

**Comment by gpedro** [comment]
i keep these keywords in the code to avoid problems when users upgrade the version and forget about adding this config

**Comment by slawkens** [comment]
Thanks one more time.

**Pull request merged**
